# Generated by Django 4.0.2 on 2022-02-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birth', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('matches', models.ManyToManyField(to='starway_app.Zodiac')),
            ],
        ),
    ]
