# Generated by Django 4.0.2 on 2022-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starway_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='matches',
            field=models.ManyToManyField(blank=True, to='starway_app.Zodiac'),
        ),
    ]
