# Generated by Django 4.0.2 on 2022-02-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starway_app', '0002_alter_zodiac_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiac',
            name='planet',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
