# Generated by Django 4.0.2 on 2022-02-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starway_app', '0003_zodiac_planet_alter_zodiac_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
