# Generated by Django 4.0.2 on 2022-02-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starway_app', '0005_alter_zodiac_description_alter_zodiac_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiac',
            name='dates',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
