# Generated by Django 4.0.2 on 2022-02-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starway_app', '0006_zodiac_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zodiac',
            old_name='dates',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='zodiac',
            name='start_date',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
