# Generated by Django 4.0.2 on 2022-02-17 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starway_app', '0007_rename_dates_zodiac_end_date_zodiac_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zodiac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starway_app.zodiac'),
        ),
    ]
